export type ObservabilityErrorCode =
  | 'OBSERVABILITY_SAMPLE_INVALID'
  | 'OBSERVABILITY_CPU_CORE_DUPLICATE'
  | 'OBSERVABILITY_CPU_CORE_COUNT_MISMATCH'
  | 'OBSERVABILITY_MEMORY_RANGE_INVALID'
  | 'OBSERVABILITY_VOLUME_RANGE_INVALID'
  | 'OBSERVABILITY_SNAPSHOT_INVALID'
  | 'OBSERVABILITY_HISTORY_LIMIT_INVALID'
  | 'OBSERVABILITY_HISTORY_TIME_REGRESSION'
  | 'OBSERVABILITY_DOWNSAMPLE_LIMIT_INVALID'
  | 'OBSERVABILITY_PERSISTENCE_INVALID'
  | 'OBSERVABILITY_PERSISTENCE_FAILED'
  | 'OBSERVABILITY_LONG_WINDOW_PREDECESSOR_INVALID'
  | 'OBSERVABILITY_LONG_WINDOW_SAMPLE_INVALID'
  | 'OBSERVABILITY_LONG_WINDOW_DIGEST_MISMATCH'
  | 'OBSERVABILITY_LONG_WINDOW_LIMIT_INVALID'
  | 'OBSERVABILITY_LONG_WINDOW_TIME_NOT_INCREASING'
  | 'OBSERVABILITY_LONG_WINDOW_CHAIN_MISMATCH'
  | 'OBSERVABILITY_LONG_WINDOW_PROFILE_INVALID'
  | 'OBSERVABILITY_LONG_WINDOW_PERSISTENCE_INVALID'
  | 'OBSERVABILITY_LATENCY_RECEIPT_BINDING_INVALID'
  | 'OBSERVABILITY_LATENCY_DURATION_MISMATCH'
  | 'OBSERVABILITY_LATENCY_RECEIPT_INVALID'

export class ObservabilityError extends Error {
  readonly code: ObservabilityErrorCode

  constructor(code: ObservabilityErrorCode, cause?: unknown) {
    super(code, cause === undefined ? undefined : { cause })
    this.name = 'ObservabilityError'
    this.code = code
  }
}
