[CmdletBinding()]
param([AllowNull()][string]$TestRoot)
Set-StrictMode -Version 2.0
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'PostGsManagerRemovalObservationV2.Common.ps1')
if([string]::IsNullOrWhiteSpace($TestRoot)){$TestRoot=Join-Path $PSScriptRoot '..\..\..\..\.codex-temp\qualification'}
$results=New-Object System.Collections.Generic.List[string]
function Add-PostRemovalSelfTestResult{param([Parameter(Mandatory)][string]$Name)[void]$results.Add($Name)}
function Assert-PostRemovalSelfTest{param([Parameter(Mandatory)][bool]$Condition,[Parameter(Mandatory)][string]$Message)if(-not $Condition){throw $Message}}
function Assert-PostRemovalSelfTestFailure{param([Parameter(Mandatory)][scriptblock]$Action,[Parameter(Mandatory)][string]$ExpectedCode,[Parameter(Mandatory)][string]$Message)$actual=$null;try{[void](& $Action)}catch{$actual=Get-DysonPostRemovalV2ErrorCode -Exception $_.Exception};if([string]$actual-cne $ExpectedCode){throw($Message+'; expected='+$ExpectedCode+'; actual='+[string]$actual)}}
function Copy-PostRemovalSelfTestValue{param([Parameter(Mandatory)]$Value)return(ConvertTo-DysonQualificationV2CanonicalJson -Value $Value)|ConvertFrom-Json}
function Get-PostRemovalSelfTestDigest{param([Parameter(Mandatory)][char]$Character)return 'sha256:'+[string]::new($Character,64)}
function Update-PostRemovalSelfTestDigest{param([Parameter(Mandatory)]$Observation)$Observation.observationSha256=Get-DysonPostRemovalV2Digest -Observation $Observation;return $Observation}
function Update-PostRemovalSelfTestInventoryAndDigest{param([Parameter(Mandatory)]$Observation)$Observation.inventory.inventorySha256=Get-DysonPostRemovalV2InventoryDigest -Inventory $Observation.inventory;return Update-PostRemovalSelfTestDigest -Observation $Observation}

function New-PostRemovalSelfTestInput{
    param([Parameter(Mandatory)][datetimeoffset]$NowUtc)
    $d=@{};foreach($pair in @(@('runtime','1'),@('manifest','2'),@('checksums','3'),@('cutover','4'),@('removal','5'),@('tls','6'),@('panel','7'),@('join','8'),@('reconnect','9'),@('world','a'),@('saveReceipt','b'),@('savePair','c'),@('saveManifest','d'),@('checkpoint','e'),@('resume','f'),@('bundle','1'),@('bundleVerify','2'),@('index','3'),@('runbook','4'),@('limits','5'))){$d[[string]$pair[0]]=Get-PostRemovalSelfTestDigest -Character ([char][string]$pair[1])}
    $start=$NowUtc.AddHours(-2);$complete=$NowUtc.AddMinutes(-1);$release=[pscustomobject][ordered]@{releaseVersion='0.1.0-rc.1';subjectCommit=[string]::new('a',40);runtimePayloadSha256=$d.runtime;releaseManifestSha256=$d.manifest;releaseChecksumsSha256=$d.checksums}
    return [pscustomobject][ordered]@{
        protocol='DYSON_POST_GSMANAGER_REMOVAL_OBSERVATION_INPUT_V2';schemaVersion=2;observationId='61000000-0000-0000-0000-000000000001';runId='61000000-0000-0000-0000-000000000002';targetIdentity='fixture-dyson-vm';releaseIdentity=$release
        cutoverObservation=[pscustomobject][ordered]@{observationId='62000000-0000-0000-0000-000000000001';observationSha256=$d.cutover;qualified=$true;observedAtUtc=ConvertTo-DysonQualificationV2Utc -Value $start.AddHours(-1)}
        removalReceipt=[pscustomobject][ordered]@{receiptId='62000000-0000-0000-0000-000000000002';receiptSha256=$d.removal;outcome='removed';completedAtUtc=ConvertTo-DysonQualificationV2Utc -Value $start.AddMinutes(-10)}
        observationWindow=[pscustomobject][ordered]@{windowId='62000000-0000-0000-0000-000000000003';observerClass='independent-operator';independent=$true;startedAtUtc=ConvertTo-DysonQualificationV2Utc -Value $start;completedAtUtc=ConvertTo-DysonQualificationV2Utc -Value $complete;elapsedMonotonicSeconds=[int64](($complete-$start).TotalSeconds)}
        inventory=[pscustomobject][ordered]@{installationCount=0;scheduledTaskCount=0;serviceCount=0;listeningPortCount=0;processCount=0;scannedAtUtc=ConvertTo-DysonQualificationV2Utc -Value $start.AddMinutes(10)}
        management=[pscustomobject][ordered]@{panelOriginAddress='127.0.0.1';panelOriginPort=3001;loopbackOnly=$true;publicHost='panel.example.com';externalTlsVerified=$true;authenticatedPanelVerified=$true;tlsReceiptSha256=$d.tls;authenticatedPanelReceiptSha256=$d.panel;observedAtUtc=ConvertTo-DysonQualificationV2Utc -Value $start.AddMinutes(20)}
        game=[pscustomobject][ordered]@{publicHost='join.example.com';protocol='nebula';serverAuthoritativeJoin=$true;serverAuthoritativeReconnect=$true;reachabilityOnly=$false;joinReceiptSha256=$d.join;reconnectReceiptSha256=$d.reconnect;worldBindingSha256=$d.world;savePairSha256=$d.savePair;observedAtUtc=ConvertTo-DysonQualificationV2Utc -Value $start.AddMinutes(40)}
        reboot=[pscustomobject][ordered]@{checkpointSha256=$d.checkpoint;resumeReceiptSha256=$d.resume;newBootObserved=$true;runtimeRecovered=$true;savePairSha256=$d.savePair;observedAtUtc=ConvertTo-DysonQualificationV2Utc -Value $start.AddMinutes(60)}
        save=[pscustomobject][ordered]@{saveReceiptSha256=$d.saveReceipt;savePairSha256=$d.savePair;saveManifestSha256=$d.saveManifest;worldBindingSha256=$d.world;pairedFilesIntact=$true;observedAtUtc=ConvertTo-DysonQualificationV2Utc -Value $start.AddMinutes(90)}
        recoveryPackage=[pscustomobject][ordered]@{bundleManifestSha256=$d.bundle;verificationReceiptSha256=$d.bundleVerify;verified=$true;activationRequired=$true;activated=$false;savePairSha256=$d.savePair;observedAtUtc=ConvertTo-DysonQualificationV2Utc -Value $start.AddMinutes(100)}
        deliverables=[pscustomobject][ordered]@{evidenceIndexSha256=$d.index;runbookSha256=$d.runbook;knownLimitationsSha256=$d.limits;releaseChecksumsSha256=$d.checksums;checksumsVerified=$true;observedAtUtc=ConvertTo-DysonQualificationV2Utc -Value $complete}
        observedAtUtc=ConvertTo-DysonQualificationV2Utc -Value $complete;expiresAtUtc=ConvertTo-DysonQualificationV2Utc -Value $NowUtc.AddMinutes(29)
    }
}

$allowedRoot=[IO.Path]::GetFullPath($TestRoot);[void][IO.Directory]::CreateDirectory($allowedRoot);$fullTestRoot=[IO.Path]::GetFullPath((Join-Path $allowedRoot ('dyson-post-removal-selftest-'+[guid]::NewGuid().ToString('N'))))
if(-not $fullTestRoot.StartsWith($allowedRoot+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)){throw 'self-test path escaped'};[void][IO.Directory]::CreateDirectory($fullTestRoot)
try{
    $now=[datetimeoffset]::ParseExact('2026-09-05T14:00:00.000Z','yyyy-MM-ddTHH:mm:ss.fffZ',[Globalization.CultureInfo]::InvariantCulture,[Globalization.DateTimeStyles]::AssumeUniversal)
    $inputValue=New-PostRemovalSelfTestInput -NowUtc $now;$observation=New-DysonPostGsManagerRemovalObservationV2 -InputValue $inputValue
    $validated=Assert-DysonPostGsManagerRemovalObservationV2 -Observation $observation -ExpectedObservationId $inputValue.observationId -ExpectedRunId $inputValue.runId -ExpectedTargetIdentity $inputValue.targetIdentity -ExpectedReleaseVersion $inputValue.releaseIdentity.releaseVersion -ExpectedSubjectCommit $inputValue.releaseIdentity.subjectCommit -ExpectedRuntimePayloadSha256 $inputValue.releaseIdentity.runtimePayloadSha256 -ExpectedReleaseManifestSha256 $inputValue.releaseIdentity.releaseManifestSha256 -NowUtc $now
    Assert-PostRemovalSelfTest -Condition ([bool]$validated.qualified) -Message 'valid post-removal observation failed';Add-PostRemovalSelfTestResult 'complete-bound-observation-accepted'

    $statusOnly=Copy-PostRemovalSelfTestValue $observation;$statusOnly|Add-Member -NotePropertyName status -NotePropertyValue 'verified';[void](Update-PostRemovalSelfTestDigest $statusOnly);Assert-PostRemovalSelfTestFailure {Assert-DysonPostGsManagerRemovalObservationV2 -Observation $statusOnly -NowUtc $now} 'DYSON_POST_GSMANAGER_REMOVAL_OBSERVATION_V2_INVALID' 'status-only shortcut accepted';Add-PostRemovalSelfTestResult 'status-only-rejected'
    $onlyRemoval=Copy-PostRemovalSelfTestValue $observation;$onlyRemoval.PSObject.Properties.Remove('game');[void](Update-PostRemovalSelfTestDigest $onlyRemoval);Assert-PostRemovalSelfTestFailure {Assert-DysonPostGsManagerRemovalObservationV2 -Observation $onlyRemoval -NowUtc $now} 'DYSON_POST_GSMANAGER_REMOVAL_OBSERVATION_V2_INVALID' 'removal-only evidence accepted';Add-PostRemovalSelfTestResult 'removal-receipt-alone-rejected'
    $badCutover=Copy-PostRemovalSelfTestValue $observation;$badCutover.cutoverObservation.qualified=$false;[void](Update-PostRemovalSelfTestDigest $badCutover);Assert-PostRemovalSelfTestFailure {Assert-DysonPostGsManagerRemovalObservationV2 -Observation $badCutover -NowUtc $now} 'DYSON_POST_GSMANAGER_REMOVAL_OBSERVATION_V2_CUTOVER_INVALID' 'unqualified cutover accepted';Add-PostRemovalSelfTestResult 'qualified-cutover-required'

    foreach($countName in @('installationCount','scheduledTaskCount','serviceCount','listeningPortCount','processCount')){$bad=Copy-PostRemovalSelfTestValue $observation;$bad.inventory.$countName=1;[void](Update-PostRemovalSelfTestInventoryAndDigest $bad);Assert-PostRemovalSelfTestFailure {Assert-DysonPostGsManagerRemovalObservationV2 -Observation $bad -NowUtc $now} 'DYSON_POST_GSMANAGER_REMOVAL_OBSERVATION_V2_RESIDUAL_AUTHORITY' ('residual '+$countName+' accepted')};Add-PostRemovalSelfTestResult 'all-five-residual-authority-counts-rejected-after-redigest'
    $badManagement=Copy-PostRemovalSelfTestValue $observation;$badManagement.management.panelOriginAddress='0.0.0.0';[void](Update-PostRemovalSelfTestDigest $badManagement);Assert-PostRemovalSelfTestFailure {Assert-DysonPostGsManagerRemovalObservationV2 -Observation $badManagement -NowUtc $now} 'DYSON_POST_GSMANAGER_REMOVAL_OBSERVATION_V2_MANAGEMENT_INVALID' 'public panel origin accepted';Add-PostRemovalSelfTestResult 'loopback-origin-and-external-tls-required'
    $reachability=Copy-PostRemovalSelfTestValue $observation;$reachability.game.reachabilityOnly=$true;$reachability.game.serverAuthoritativeJoin=$false;[void](Update-PostRemovalSelfTestDigest $reachability);Assert-PostRemovalSelfTestFailure {Assert-DysonPostGsManagerRemovalObservationV2 -Observation $reachability -NowUtc $now} 'DYSON_POST_GSMANAGER_REMOVAL_OBSERVATION_V2_GAME_INVALID' 'HTTP/TCP reachability accepted';Add-PostRemovalSelfTestResult 'real-nebula-join-reconnect-required'

    $crossRun=Copy-PostRemovalSelfTestValue $observation;$crossRun.removalReceipt.subjectBindingSha256=Get-PostRemovalSelfTestDigest 'f';[void](Update-PostRemovalSelfTestDigest $crossRun);Assert-PostRemovalSelfTestFailure {Assert-DysonPostGsManagerRemovalObservationV2 -Observation $crossRun -NowUtc $now} 'DYSON_POST_GSMANAGER_REMOVAL_OBSERVATION_V2_REMOVAL_INVALID' 'cross-run receipt accepted';Add-PostRemovalSelfTestResult 'cross-run-splice-rejected'
    $crossRelease=Copy-PostRemovalSelfTestValue $observation;$crossRelease.management.subjectBindingSha256=Get-PostRemovalSelfTestDigest 'e';[void](Update-PostRemovalSelfTestDigest $crossRelease);Assert-PostRemovalSelfTestFailure {Assert-DysonPostGsManagerRemovalObservationV2 -Observation $crossRelease -NowUtc $now} 'DYSON_POST_GSMANAGER_REMOVAL_OBSERVATION_V2_MANAGEMENT_INVALID' 'cross-release management accepted';Add-PostRemovalSelfTestResult 'cross-release-splice-rejected'
    $crossSave=Copy-PostRemovalSelfTestValue $observation;$crossSave.game.savePairSha256=Get-PostRemovalSelfTestDigest '0';[void](Update-PostRemovalSelfTestDigest $crossSave);Assert-PostRemovalSelfTestFailure {Assert-DysonPostGsManagerRemovalObservationV2 -Observation $crossSave -NowUtc $now} 'DYSON_POST_GSMANAGER_REMOVAL_OBSERVATION_V2_SAVE_INVALID' 'cross-save splice accepted';Add-PostRemovalSelfTestResult 'game-reboot-save-pair-binding-enforced'

    foreach($property in @('verified','activated')){$badRecovery=Copy-PostRemovalSelfTestValue $observation;if($property-ceq'verified'){$badRecovery.recoveryPackage.verified=$false}else{$badRecovery.recoveryPackage.activated=$true};[void](Update-PostRemovalSelfTestDigest $badRecovery);Assert-PostRemovalSelfTestFailure {Assert-DysonPostGsManagerRemovalObservationV2 -Observation $badRecovery -NowUtc $now} 'DYSON_POST_GSMANAGER_REMOVAL_OBSERVATION_V2_RECOVERY_INVALID' ('unsafe recovery '+$property+' accepted')};Add-PostRemovalSelfTestResult 'verified-but-not-activated-recovery-package-required'
    $badReboot=Copy-PostRemovalSelfTestValue $observation;$badReboot.reboot.newBootObserved=$false;[void](Update-PostRemovalSelfTestDigest $badReboot);Assert-PostRemovalSelfTestFailure {Assert-DysonPostGsManagerRemovalObservationV2 -Observation $badReboot -NowUtc $now} 'DYSON_POST_GSMANAGER_REMOVAL_OBSERVATION_V2_REBOOT_INVALID' 'no-reboot observation accepted';Add-PostRemovalSelfTestResult 'reboot-resume-required'
    $badDeliverables=Copy-PostRemovalSelfTestValue $observation;$badDeliverables.deliverables.releaseChecksumsSha256=Get-PostRemovalSelfTestDigest '0';[void](Update-PostRemovalSelfTestDigest $badDeliverables);Assert-PostRemovalSelfTestFailure {Assert-DysonPostGsManagerRemovalObservationV2 -Observation $badDeliverables -NowUtc $now} 'DYSON_POST_GSMANAGER_REMOVAL_OBSERVATION_V2_DELIVERABLES_INVALID' 'mismatched release checksums accepted';Add-PostRemovalSelfTestResult 'evidence-runbook-limitations-checksums-required'
    $badWindow=Copy-PostRemovalSelfTestValue $observation;$badWindow.observationWindow.elapsedMonotonicSeconds=30;[void](Update-PostRemovalSelfTestDigest $badWindow);Assert-PostRemovalSelfTestFailure {Assert-DysonPostGsManagerRemovalObservationV2 -Observation $badWindow -NowUtc $now} 'DYSON_POST_GSMANAGER_REMOVAL_OBSERVATION_V2_WINDOW_INVALID' 'short observation window accepted';Add-PostRemovalSelfTestResult 'independent-minimum-window-required'
    $outOfOrder=Copy-PostRemovalSelfTestValue $observation;$outOfOrder.management.observedAtUtc=ConvertTo-DysonQualificationV2Utc -Value $now.AddMinutes(-75);[void](Update-PostRemovalSelfTestDigest $outOfOrder);Assert-PostRemovalSelfTestFailure {Assert-DysonPostGsManagerRemovalObservationV2 -Observation $outOfOrder -NowUtc $now} 'DYSON_POST_GSMANAGER_REMOVAL_OBSERVATION_V2_TIMING_INVALID' 're-digested out-of-order evidence accepted';Add-PostRemovalSelfTestResult 'strict-evidence-sequence-enforced-after-redigest'
    Assert-PostRemovalSelfTestFailure {Assert-DysonPostGsManagerRemovalObservationV2 -Observation $observation -NowUtc $now.AddHours(2)} 'DYSON_POST_GSMANAGER_REMOVAL_OBSERVATION_V2_STALE' 'expired observation accepted';Add-PostRemovalSelfTestResult 'expiry-enforced'
    $digestTamper=Copy-PostRemovalSelfTestValue $observation;$digestTamper.observationSha256=Get-PostRemovalSelfTestDigest '0';Assert-PostRemovalSelfTestFailure {Assert-DysonPostGsManagerRemovalObservationV2 -Observation $digestTamper -NowUtc $now} 'DYSON_POST_GSMANAGER_REMOVAL_OBSERVATION_V2_DIGEST_INVALID' 'self digest tamper accepted';Add-PostRemovalSelfTestResult 'self-digest-enforced'

    foreach($case in @(@('ExpectedRunId','61000000-0000-0000-0000-000000000099'),@('ExpectedTargetIdentity','other-fixture-target'),@('ExpectedReleaseVersion','9.9.9'),@('ExpectedSubjectCommit',[string]::new('b',40)),@('ExpectedRuntimePayloadSha256',(Get-PostRemovalSelfTestDigest '0')))){$splat=@{Observation=$observation;NowUtc=$now};$splat[[string]$case[0]]=[string]$case[1];Assert-PostRemovalSelfTestFailure {Assert-DysonPostGsManagerRemovalObservationV2 @splat} 'DYSON_POST_GSMANAGER_REMOVAL_OBSERVATION_V2_BINDING_INVALID' ('expected binding '+$case[0]+' mismatch accepted')};Add-PostRemovalSelfTestResult 'independent-expected-bindings-enforced'
    Assert-PostRemovalSelfTestFailure {ConvertFrom-DysonPostRemovalV2StrictJson -Text '{"protocol":"one","\u0070rotocol":"two"}'} 'DYSON_POST_GSMANAGER_REMOVAL_OBSERVATION_V2_DUPLICATE_JSON_KEY' 'duplicate JSON accepted';Add-PostRemovalSelfTestResult 'duplicate-json-key-rejected'

    $inputPath=Join-Path $fullTestRoot 'input.json';$outputPath=Join-Path $fullTestRoot 'observation.json';[IO.File]::WriteAllText($inputPath,(ConvertTo-DysonQualificationV2CanonicalJson $inputValue),(New-Object Text.UTF8Encoding -ArgumentList $false))
    $generator=&(Join-Path $PSScriptRoot 'New-DysonPostGsManagerRemovalObservationV2.ps1') -InputPath $inputPath -OutputPath $outputPath -NowUtc $now|ConvertFrom-Json;$validator=&(Join-Path $PSScriptRoot 'Test-DysonPostGsManagerRemovalObservationV2.ps1') -ObservationPath $outputPath -ExpectedObservationId $inputValue.observationId -ExpectedRunId $inputValue.runId -ExpectedTargetIdentity $inputValue.targetIdentity -ExpectedReleaseVersion $inputValue.releaseIdentity.releaseVersion -ExpectedSubjectCommit $inputValue.releaseIdentity.subjectCommit -ExpectedRuntimePayloadSha256 $inputValue.releaseIdentity.runtimePayloadSha256 -ExpectedReleaseManifestSha256 $inputValue.releaseIdentity.releaseManifestSha256 -NowUtc $now|ConvertFrom-Json
    Assert-PostRemovalSelfTest -Condition ([bool]$generator.qualified -and [bool]$validator.qualified -and -not[bool]$validator.networkTouched -and -not[bool]$validator.productionChanged) -Message 'create-new or read-only validation failed';Assert-PostRemovalSelfTestFailure {&(Join-Path $PSScriptRoot 'New-DysonPostGsManagerRemovalObservationV2.ps1') -InputPath $inputPath -OutputPath $outputPath -NowUtc $now} 'DYSON_POST_GSMANAGER_REMOVAL_OBSERVATION_V2_OUTPUT_EXISTS' 'existing observation overwritten';Add-PostRemovalSelfTestResult 'canonical-create-new-and-read-only-validator'
    $schema=Get-Content -Raw -LiteralPath(Join-Path $PSScriptRoot 'dyson-post-gsmanager-removal-observation-v2.schema.json')|ConvertFrom-Json;Assert-PostRemovalSelfTest -Condition ([string]$schema.properties.protocol.const-ceq $script:DysonPostRemovalV2Protocol -and -not[bool]$schema.additionalProperties -and $null-eq $schema.properties.PSObject.Properties['status']) -Message 'schema drift';Add-PostRemovalSelfTestResult 'schema-exact-and-status-free'
    [pscustomobject][ordered]@{protocol='DYSON_POST_GSMANAGER_REMOVAL_OBSERVATION_SELFTEST_V2';schemaVersion=2;status='passed';runtime='Windows PowerShell 5.1 compatible';runtimeVersion=$PSVersionTable.PSVersion.ToString();testCount=$results.Count;passedCount=$results.Count;tests=@($results|ForEach-Object{$_});fixtureManagementHost='panel.example.com';fixtureGameHost='join.example.com';fixtureOnly=$true;networkTouched=$false;productionChanged=$false}|ConvertTo-Json -Depth 8 -Compress
}finally{if(Test-Path -LiteralPath $fullTestRoot){$resolved=[IO.Path]::GetFullPath($fullTestRoot);if($resolved.StartsWith($allowedRoot+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase) -and [IO.Path]::GetFileName($resolved)-cmatch'^dyson-post-removal-selftest-[0-9a-f]{32}$'){Remove-Item -LiteralPath $resolved -Recurse -Force}}}
